name: MeritOne
options:
  bundleIdPrefix: com.meritmd
  deploymentTarget:
    iOS: "16.0"
targets:
  MeritOne:
    type: application
    platform: iOS
    sources:
      - path: MeritOne/Sources
    resources:
      - path: MeritOne/Resources
    info:
      path: MeritOne/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleDisplayName: MeritOne
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.meritmd.meritone
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: 5.0
