// Mirrors the in-scope Supabase tables. `key` is the Appwrite collection id
// (and matches the Supabase table name so the migration can map 1:1).
//
// access:
//   'catalog' - readable by any signed-in user (services, products, rewards, ...)
//   'owned'   - per-document read permission granted to the owning patient
//   'staff'   - staff team only

export const COLLECTIONS = [
  {
    key: 'practices',
    name: 'Practices',
    access: 'catalog',
    attributes: [
      { key: 'name', type: 'string', size: 255, required: true },
      { key: 'created_at', type: 'datetime', required: false },
    ],
  },
  {
    key: 'patients',
    name: 'Patients',
    access: 'owned',
    attributes: [
      { key: 'practice_id', type: 'string', size: 64, required: true },
      { key: 'full_name', type: 'string', size: 255, required: true },
      { key: 'phone', type: 'string', size: 64, required: false },
      { key: 'email', type: 'string', size: 320, required: true },
      { key: 'referral_code', type: 'string', size: 32, required: true },
      { key: 'referred_by', type: 'string', size: 64, required: false },
      { key: 'expo_push_token', type: 'string', size: 512, required: false },
      { key: 'square_customer_id', type: 'string', size: 128, required: false },
      { key: 'created_at', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'idx_email', type: 'key', attributes: ['email'] },
      { key: 'idx_referral_code', type: 'key', attributes: ['referral_code'] },
    ],
  },
  {
    key: 'staff',
    name: 'Staff',
    access: 'staff',
    attributes: [
      { key: 'practice_id', type: 'string', size: 64, required: true },
      { key: 'full_name', type: 'string', size: 255, required: true },
      { key: 'role', type: 'string', size: 64, required: true },
      { key: 'created_at', type: 'datetime', required: false },
    ],
  },
  {
    key: 'loyalty_settings',
    name: 'Loyalty Settings',
    access: 'catalog',
    attributes: [
      { key: 'practice_id', type: 'string', size: 64, required: true },
      { key: 'points_per_dollar', type: 'float', required: true },
      { key: 'points_to_dollar_redemption', type: 'float', required: true },
      { key: 'referral_bonus_points', type: 'integer', required: true },
      { key: 'updated_at', type: 'datetime', required: false },
      { key: 'updated_by', type: 'string', size: 64, required: false },
    ],
    indexes: [{ key: 'idx_practice', type: 'key', attributes: ['practice_id'] }],
  },
  {
    key: 'milestones',
    name: 'Milestones',
    access: 'catalog',
    attributes: [
      { key: 'practice_id', type: 'string', size: 64, required: true },
      { key: 'visit_count', type: 'integer', required: true },
      { key: 'bonus_points', type: 'integer', required: true },
      { key: 'label', type: 'string', size: 255, required: true },
      { key: 'active', type: 'boolean', required: true },
      { key: 'created_at', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'idx_practice_active', type: 'key', attributes: ['practice_id', 'active'] },
      { key: 'idx_visit_count', type: 'key', attributes: ['visit_count'] },
    ],
  },
  {
    key: 'rewards',
    name: 'Rewards',
    access: 'catalog',
    attributes: [
      { key: 'practice_id', type: 'string', size: 64, required: true },
      { key: 'title', type: 'string', size: 255, required: true },
      { key: 'description', type: 'string', size: 2000, required: false },
      { key: 'points_cost', type: 'integer', required: true },
      { key: 'credit_value', type: 'float', required: true },
      { key: 'image_url', type: 'string', size: 1024, required: false },
      { key: 'active', type: 'boolean', required: true },
      { key: 'created_at', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'idx_practice_active', type: 'key', attributes: ['practice_id', 'active'] },
      { key: 'idx_points_cost', type: 'key', attributes: ['points_cost'] },
    ],
  },
  {
    key: 'services',
    name: 'Services',
    access: 'catalog',
    attributes: [
      { key: 'practice_id', type: 'string', size: 64, required: true },
      { key: 'name', type: 'string', size: 255, required: true },
      { key: 'description', type: 'string', size: 2000, required: false },
      { key: 'price', type: 'float', required: false },
      { key: 'member_price', type: 'float', required: false },
      { key: 'booking_url', type: 'string', size: 1024, required: true },
      { key: 'category', type: 'string', size: 128, required: false },
      { key: 'featured', type: 'boolean', required: true },
      { key: 'active', type: 'boolean', required: true },
      { key: 'created_at', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'idx_practice_active', type: 'key', attributes: ['practice_id', 'active'] },
      { key: 'idx_featured', type: 'key', attributes: ['featured'] },
    ],
  },
  {
    key: 'products',
    name: 'Products',
    access: 'catalog',
    attributes: [
      { key: 'practice_id', type: 'string', size: 64, required: true },
      { key: 'name', type: 'string', size: 255, required: true },
      { key: 'description', type: 'string', size: 2000, required: false },
      { key: 'price', type: 'float', required: true },
      { key: 'image_url', type: 'string', size: 1024, required: false },
      { key: 'active', type: 'boolean', required: true },
      { key: 'created_at', type: 'datetime', required: false },
    ],
    indexes: [{ key: 'idx_practice_active', type: 'key', attributes: ['practice_id', 'active'] }],
  },
  {
    key: 'membership_plans',
    name: 'Membership Plans',
    access: 'catalog',
    attributes: [
      { key: 'practice_id', type: 'string', size: 64, required: true },
      { key: 'name', type: 'string', size: 255, required: true },
      { key: 'description', type: 'string', size: 2000, required: false },
      { key: 'monthly_price', type: 'float', required: false },
      { key: 'square_plan_variation_id', type: 'string', size: 128, required: false },
      { key: 'active', type: 'boolean', required: true },
      { key: 'created_at', type: 'datetime', required: false },
    ],
    indexes: [{ key: 'idx_practice_active', type: 'key', attributes: ['practice_id', 'active'] }],
  },
  {
    key: 'points_ledger',
    name: 'Points Ledger',
    access: 'owned',
    ownerField: 'patient_id',
    attributes: [
      { key: 'patient_id', type: 'string', size: 64, required: true },
      { key: 'practice_id', type: 'string', size: 64, required: true },
      { key: 'entry_type', type: 'string', size: 32, required: true },
      { key: 'points', type: 'integer', required: true },
      { key: 'dollar_amount', type: 'float', required: false },
      { key: 'reference_id', type: 'string', size: 64, required: false },
      { key: 'created_by', type: 'string', size: 64, required: false },
      { key: 'note', type: 'string', size: 1000, required: false },
      { key: 'created_at', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'idx_patient', type: 'key', attributes: ['patient_id'] },
      { key: 'idx_entry_type', type: 'key', attributes: ['entry_type'] },
    ],
  },
  {
    key: 'redemptions',
    name: 'Redemptions',
    access: 'owned',
    ownerField: 'patient_id',
    attributes: [
      { key: 'patient_id', type: 'string', size: 64, required: true },
      { key: 'reward_id', type: 'string', size: 64, required: true },
      { key: 'points_spent', type: 'integer', required: true },
      { key: 'credit_value', type: 'float', required: true },
      { key: 'code', type: 'string', size: 32, required: true },
      { key: 'status', type: 'string', size: 32, required: true },
      { key: 'redeemed_at', type: 'datetime', required: false },
      { key: 'redeemed_by', type: 'string', size: 64, required: false },
      { key: 'created_at', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'idx_patient', type: 'key', attributes: ['patient_id'] },
      { key: 'idx_code', type: 'key', attributes: ['code'] },
    ],
  },
  {
    key: 'patient_memberships',
    name: 'Patient Memberships',
    access: 'owned',
    ownerField: 'patient_id',
    attributes: [
      { key: 'patient_id', type: 'string', size: 64, required: true },
      { key: 'plan_id', type: 'string', size: 64, required: false },
      { key: 'square_customer_id', type: 'string', size: 128, required: false },
      { key: 'square_subscription_id', type: 'string', size: 128, required: false },
      { key: 'status', type: 'string', size: 32, required: true },
      { key: 'current_period_end', type: 'datetime', required: false },
      { key: 'created_at', type: 'datetime', required: false },
      { key: 'updated_at', type: 'datetime', required: false },
    ],
    indexes: [{ key: 'idx_patient_status', type: 'key', attributes: ['patient_id', 'status'] }],
  },
]
